### ISSUE TITLE
json source and new tags

### ISSUE THREAD

**Issue by antonioaltamura** [henrychavez/materialize-tags#12]
Hi, it looks like this plugin doesn't allow a json source for tags AND the possibility for the user of typing new tags. Am I wrong?

**Comment by henrychavez** [comment]
Have you seen the example page?

On Friday, 4 December 2015, alfredopacino notifications@github.com wrote:

> Hi, it looks like this plugin doesn't allow a json source for tags AND the
> possibility for the user of typing new tags. Am I wrong?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/henrychavez/materialize-tags/issues/12.

## 

Henry G. Chávez Vergara.
Design, Web & Mobile Development
Phone: +(51) 944119329
Email: henry19.chavez@gmail.com
Lima - Perú

**Comment by antonioaltamura** [comment]
I saw it, and I saw the typehead.js example doesn't allow to type new tags.
There is some kind of documentation?

**Comment by antonioaltamura** [comment]
can I get some help please? otherwise I have to adapt another jquery plugin to materialize style, it's a lot of work and I'm not even sure are completely compatible..

**Comment by henrychavez** [comment]
you need to try passing the option freeInput:true when you initialize the
plugin

2015-12-08 19:25 GMT-05:00 alfredopacino notifications@github.com:

> can I get some help please? otherwise I have to adapt another jquery
> plugin to materialize style, it's a lot of work and I'm not even sure are
> completely compatible..
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/henrychavez/materialize-tags/issues/12#issuecomment-163065904
> .

## 

Henry G. Chávez Vergara.
Design, Web & Mobile Development
Phone: +(51) 944119329
Email: henry19.chavez@gmail.com
Lima - Perú

**Comment by antonioaltamura** [comment]
thanks I will try. There is no documentation about those params?

**Comment by henrychavez** [comment]
Yes, i forget put the documentation in the website. I'm doing right now!

2015-12-09 3:26 GMT-05:00 alfredopacino notifications@github.com:

> thanks I will try. There is no documentation about those params?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/henrychavez/materialize-tags/issues/12#issuecomment-163148845
> .

## 

Henry G. Chávez Vergara.
Design, Web & Mobile Development
Phone: +(51) 944119329
Email: henry19.chavez@gmail.com
Lima - Perú

**Comment by henrychavez** [comment]
now you can see all the documentation here
http://henrychavez.github.io/materialize-tags/examples/

2015-12-09 3:28 GMT-05:00 Henry Chavez V. henry19.chavez@gmail.com:

> Yes, i forget put the documentation in the website. I'm doing right now!
> 
> 2015-12-09 3:26 GMT-05:00 alfredopacino notifications@github.com:
> 
> > thanks I will try. There is no documentation about those params?
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/henrychavez/materialize-tags/issues/12#issuecomment-163148845
> > .
> 
> ## 
> 
> Henry G. Chávez Vergara.
> Design, Web & Mobile Development
> Phone: +(51) 944119329
> Email: henry19.chavez@gmail.com
> Lima - Perú

## 

Henry G. Chávez Vergara.
Design, Web & Mobile Development
Phone: +(51) 944119329
Email: henry19.chavez@gmail.com
Lima - Perú

**Comment by alfredopacino** [comment]
very thanks! one last thing: my form is retrieved using ajax, so the materialize tags plugin init doesn't works fine.
there is a way to initialize my inputs fields? something like $('input#tags').materialize_tags_init();

**Comment by antonioaltamura** [comment]
Hi, if I initialize the plugin with 

```
var qualification = new Bloodhound({
        datumTokenizer: Bloodhound.tokenizers.obj.whitespace('name'),
        queryTokenizer: Bloodhound.tokenizers.whitespace,
        remote: {
            url: 'fake_endpoint/reg_qualification.php?q=%QUERY',
            wildcard: '%QUERY'
        }
    });
    qualification.initialize();

    $('input#qualification').materialtags({
        itemValue: 'value',
        itemText: 'value',
        typeaheadjs: {
            name: 'name',
            display: 'value',
            source: qualification.ttAdapter()
        }

    });
```

where can I define     freeInput: true?

**Comment by henrychavez** [comment]
next to itemText

**Comment by antonioaltamura** [comment]
so in your documentation about Typeahead what are valid parameter

```
    $('input').materialtags({
       ###settings
    });
```

are still valid for

```
    $('input').tagsinput({
       ###settings
    });
```

what are the differences?
