### ISSUE TITLE
freeinput tag reappears after adding

### ISSUE THREAD

**Issue by antonioaltamura** [henrychavez/materialize-tags#13]
Hi, materialize tags have this bug too
https://github.com/bootstrap-tagsinput/bootstrap-tagsinput/issues/236
but the @xplicit afterSelect solution doesn't work

**Comment by antonioaltamura** [comment]
thanks

**Comment by patricklindsay** [comment]
The referenced PR fixes the issue but it hasn't yet been merged.

This shouldn't be closed.
