### ISSUE TITLE
input text field issue

### ISSUE THREAD

**Issue by antonioaltamura** [henrychavez/materialize-tags#16]
Hi
sometimes (sometimes it happens, sometimes not) I click on the input type=text, the label became "active" but the input field isn't active (I can't directly type on it)
In other words the border-bottom stays grey

(i'm on chrome 47.0.2526.106 m / win7)

![a](https://cloud.githubusercontent.com/assets/6325475/11946441/17e575fc-a85b-11e5-9fde-f3a9022ccd49.png)

**Comment by edanweis** [comment]
I had this problem and solved it with `pointer-events: none` css applied to the `<label>` of the input.
