### ISSUE TITLE
Multiline styling issue

### ISSUE THREAD

**Issue by markmooibroek** [henrychavez/materialize-tags#20]
Slightly overlaps the label.

<img width="172" alt="screen shot 2016-01-02 at 07 01 10" src="https://cloud.githubusercontent.com/assets/1412238/12073391/bb4c8eb2-b11e-11e5-9292-4a4f23678e28.png">

**Comment by DEKHTIARJonathan** [comment]
The library has been updated many times since you opened your issue. I'm closing it.
If it is still relevant, do not hesitate to re-open an issue.
