### ISSUE TITLE
Material Tags with autocomplete

### ISSUE THREAD

**Issue by armandomendivil** [henrychavez/materialize-tags#22]
Is there a reason that when you (press tab?) you use: $input.val(''): and when you use "click", you use: typeahead('val', '')?

I used an autocomplete to create tags and when I (pressed tab?) the behavior was different from the click. 

The solution was to use typeahead('val', '') for both cases.

**Comment by henrychavez** [comment]
You are right the tab event was implemented recently and I miss that

On Wednesday, 10 February 2016, armandomendivil notifications@github.com
wrote:

> Is there a reason that when you (press tab?) you use: $input.val(''): and
> when you use "click", you use: typeahead('val', '')?
> 
> I used an autocomplete to create tags and when I (pressed tab?) the
> behavior was different from the click.
> 
> The solution was to use typeahead('val', '') for both cases.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/henrychavez/materialize-tags/issues/22.

## 

Henry G. Chávez Vergara.
Design, Web & Mobile Development
Phone: +(51) 944119329
Email: henry19.chavez@gmail.com
Lima - Perú
