### ISSUE TITLE
Add tag in correct place

### ISSUE THREAD

**Issue by itsmanuelrc** [henrychavez/materialize-tags#23]
I'm trying to add a new tag moving between the tags and see that the new record is saved in the last position and is not the desired position. Can you fix this? [screenshoot](http://screencloud.net/v/3ORg)

**Comment by DEKHTIARJonathan** [comment]
The library has been updated many times since you opened your issue. I'm closing it.
If it is still relevant, do not hesitate to re-open an issue.
