### ISSUE TITLE
Default tags / suggestions not shown on focus when minLength: 0 for typeahead

### ISSUE THREAD

**Issue by gcmurphy** [henrychavez/materialize-tags#24]
I've attempted to configure typeahead with this library using minLength: 0, as per https://github.com/twitter/typeahead.js/pull/719. The default tag list is not shown on focus. I've not been able to overwrite the $('#tag').focus() events to trigger the typeahead to open when using this library.

**Comment by DEKHTIARJonathan** [comment]
The library has been updated many times since you opened your issue. I'm closing it.
If it is still relevant, do not hesitate to re-open an issue.
