### ISSUE TITLE
freeInput: false with completeKey should add the top suggestion

### ISSUE THREAD

**Issue by gcmurphy** [henrychavez/materialize-tags#25]
I'm trying to limit user input to a fix list of tags with autocomplete. If the user presses enter I want the top suggestion to be added to the list. 

The behaviour I'm currently seeing is that when  freeInput is disabled and a partial match for a tag is entered followed by the complete key stroke. The focus is shifted to the next field in the form rather than than adding the top suggestion that matches.

**Comment by DEKHTIARJonathan** [comment]
See our documentation "autoselect" parameter has been added in #34
