### ISSUE TITLE
Custom templates

### ISSUE THREAD

**Issue by Kelin2025** [henrychavez/materialize-tags#26]
Did you add custom templates support as in original Twitter typeahead.js?
In your demo it's not shown. 
![image](https://cloud.githubusercontent.com/assets/4208480/14190634/7ee4973e-f79c-11e5-9e79-9fc5be8d0496.png)
If not realized, can you add it, please?

Thank you.

**Comment by twhetzel** [comment]
I've tried header, footer, and notFound from here https://github.com/twitter/typeahead.js/blob/master/doc/jquery_typeahead.md#datasets and these work.
