### ISSUE TITLE
Can´t initialize in jQuerys ready function

### ISSUE THREAD

**Issue by julianpomper** [henrychavez/materialize-tags#29]
I am trying to initialize it after I get data from the server(ajax) or in jQuerys ready function, but it only works when I write it outside of every function.
And I want to update the value(and the tags) but it only works when I fill it in static oder manually

**Comment by DEKHTIARJonathan** [comment]
Could you please provide an example.
Can't understand your problem

**Comment by DEKHTIARJonathan** [comment]
Closing because of not responding
