### ISSUE TITLE
Can multiple data sources be used

### ISSUE THREAD

**Issue by twhetzel** [henrychavez/materialize-tags#31]
I'd like to use data from multiple data sources similar to the example from [typeahead.js](http://twitter.github.io/typeahead.js/examples/#multiple-datasets)  Is this possible? I've tried a few options, but without success and didn't see an example in the docs.

**Comment by DEKHTIARJonathan** [comment]
@twhetzel your need is still alive ? Or I should close the ticket ?

**Comment by DEKHTIARJonathan** [comment]
Closing because of not responding
