### ISSUE TITLE
Typeahead 0.11.1 support + typo in docs

### ISSUE THREAD

**Issue by patricklindsay** [henrychavez/materialize-tags#32]
1. [Source option docs](http://henrychavez.github.io/materialize-tags/examples/) has two typos. Docs say `typeahead` when it should read `typeaheadjs`
2. When using Typeahead (0.11.1) styling issues occur with the suggestions as typeahead markup has slightly changed.

Both issues are detailed in this [StackOverflow answer](http://stackoverflow.com/a/35733112)

**Comment by jcrichard** [comment]
also can we use these option  with 
hint: true,
highlight: true,

It is not working in my case

**Comment by henrychavez** [comment]
This problems with Typeahead was solved in the last update
