### ISSUE TITLE
Opening a Travis-CI and Gemnasium Repository

### ISSUE THREAD

**Issue by DEKHTIARJonathan** [henrychavez/materialize-tags#37]
Hello @henrychavez,

Sorry to disturb again ! Could you please create an account there : 
- https://travis-ci.org/
- https://gemnasium.com/

Can't do it by myself, I'm not the repo admin

100% Free and it will be useful for me to set up CI tools ;) Thanks buddy !

**Comment by henrychavez** [comment]
Hi @DEKHTIARJonathan the accounts were created.

Let me now if u need something else.

**Comment by DEKHTIARJonathan** [comment]
@henrychavez look at the readme, but I think it's good.

Thanks a lot dude.
