### ISSUE TITLE
how do I set tags after $(document).ready()

### ISSUE THREAD

**Issue by jalasem** [henrychavez/materialize-tags#38]
how do I set tags after $(document).ready()

Please I need an urgent reply

**Comment by DEKHTIARJonathan** [comment]
You can have a look to our demo-page : http://henrychavez.github.io/materialize-tags/examples/

If you look for to tune typeahead & bloodhound : https://github.com/twitter/typeahead.js

Everything is very nicely explained and clear. If you have any specific problem, please create a JS Fiddle showing your issue: https://jsfiddle.net/

Regards,

Jonathan DEKHTIAR
