### ISSUE TITLE
Works with meteor ?

### ISSUE THREAD

**Issue by udiedrichsen** [henrychavez/materialize-tags#4]
Hi,

Great package, thx !
https://atmospherejs.com/benan789/materialize-tagsinput

But I dont get this working with meteor.

I tried your basic example:
    <input type="text" value="Amsterdam,Washington,Sydney,Beijing,Cairo" data-role="materialtags" />

I seems that the initialisation is missing. On the browser it shows only:
Amsterdam,Washington,Sydney,Beijing,Cairo

in the input field without any decoration.

Would be great to have a simple example how to use in meteor.

**Comment by MagneticMule** [comment]
Yep, doesn't work on Meteor here either.Any help would be appreciated.

**Comment by MagneticMule** [comment]
Ah right, as this is a jQuery plugin you need to initialize it in your Template's rendered function like so:

```
this.$('input[data-role=materialtags]'.materialtags();
```

Perhaps you could update the Docs on Atmosphere when you have the time?

**Comment by armandomendivil** [comment]
I used materialize tags on Meteor

**Comment by kwunyeung** [comment]
It works after calling the jQuery function but the close button is missing. I cannot find any options which can add the close button back. Any way to do this? Thanks!

**Comment by meyfleur** [comment]
i used css this to add close sign
`.mdi-content-clear[data-role=remove]:before{
      content: "unicode";
    }`

**Comment by DEKHTIARJonathan** [comment]
The library has been updated many times since you opened your issue. I'm closing it.
If it is still relevant, do not hesitate to re-open an issue.
