### ISSUE TITLE
Npm Version is different

### ISSUE THREAD

**Issue by matyre73** [henrychavez/materialize-tags#40]
Hi

Just aheads up your npm version css file is different to your github css file version. Under the dist folder. Are there any differences between the js files as well?

**Comment by DEKHTIARJonathan** [comment]
I don't have the control over the npm package.
@henrychavez can you have a look to this ?

Maybe it would be nice to automate publishing from travis when a tag is pushed ;)

**Comment by DEKHTIARJonathan** [comment]
@henrychavez any way you can automate the deploy toward npm with travis when a "git tag" is added ?

**Comment by henrychavez** [comment]
@DEKHTIARJonathan @matyre73 done!
