### ISSUE TITLE
On loosing focus, inputted text stays and tag-nized.

### ISSUE THREAD

**Issue by ginlime** [henrychavez/materialize-tags#42]
According to subject.  

1. input some letter in input field.

1. loose focus from input field by clicking other place.

1. inputted text changes to tag, and stays input field, too...

**Comment by DEKHTIARJonathan** [comment]
Can you make a reproducible jsfiddle ?
I don't have time to look how to reproduce this behaviour.

Thanks in advance,

Jonathan
