### ISSUE TITLE
Can't add Tag that doesn't exist in data source

### ISSUE THREAD

**Issue by attiqeurrehman** [henrychavez/materialize-tags#43]
Hi,

I am trying to maintain grades tag in an application and it works for existing data fetched from the server but when I try to add new it submits the form. I have tried to trap the **beforeItemAdd** but it doesn't stops there. Here's my code:

```
var grades = new Bloodhound({
            datumTokenizer: Bloodhound.tokenizers.obj.whitespace('name'),
            queryTokenizer: Bloodhound.tokenizers.whitespace,
            remote: {
                url: '../api/Grades?query=%QUERY',
                filter: function(list) {
                    return $.map(list, function(grade) {
                        return { name: grade.Name, id: grade.Id };
                    });
                }
            }
        });

        grades.initialize();
        var gradesOptions = {
            trimValue: true,
            maxTags: 3,
            freeInput: true,
            itemValue: 'id',
            itemText: 'name',
            typeaheadjs: {
                name: 'grades',
                displayKey: 'name',
                source: grades.ttAdapter()
            }
        };
        $('.grades').materialtags(gradesOptions);
```

Any pointers?

Thanks,
Attiqe

**Comment by DEKHTIARJonathan** [comment]
@attiqeurrehman Can you please create a JSFiddle to recreate this behaviour. I can't really help you with just a few lines ...

Thanks

**Comment by attiqeurrehman** [comment]
@DEKHTIARJonathan It's very similar to your [example ](http://henrychavez.github.io/materialize-tags/examples/)Objects as tags. If you try enter anything that doesn't exist in the data source it will not let you enter it. I will create a JSFiddle for you as well.

**Comment by DEKHTIARJonathan** [comment]
@attiqeurrehman: this functionnality has been with the commit: 5df371259ce795c4fea37b9e3dae66be690e2f15

Have a look to the modifications to see how you can use it.
