### ISSUE TITLE
free input and objects 

### ISSUE THREAD

**Issue by lleoooell** [henrychavez/materialize-tags#45]
Hello there,

Thank you for your awesome plugin...

i'm using it in two situations...

First, for an input where i don't need freeinput with objects, everything work perfectly.

Second, i use this plugin to autocomplete with tag objects, and let user create a new tag if it's not present in the suggestion list.

My problem (appears only on mobile device) is when i enter text for a tag (ex: "res" for "restaurant"), the tag shows in the list, but if i click on the suggestion (to quick select 'restaurant'), the event.item (logged with on beforeItemAdd) is only "res"...

It seems that the event triggers first the text value entered before the suggestion choice, so the suggestion choice is not triggered...

How do you handle this ?

Many thanks,

**Comment by lleoooell** [comment]
hi there, 
no advices ?

**Comment by DEKHTIARJonathan** [comment]
Hello there @lleoooell,
Sorry for taking quite a while to answer you: Summer Time. 

We have merge your modifications inside the library. We hope it will help you.

Best Regards,
