### ISSUE TITLE
Repository's settings change request

### ISSUE THREAD

**Issue by DEKHTIARJonathan** [henrychavez/materialize-tags#50]
Hello @henrychavez , could you please change the settings of the repository concerning git-pages.

It would be better to make it point toward the "docs/" folder in the master branch.

I have updated the library to work with the latest version of JQuery and Materialize. Having two branch to maintain is not very useful and not practical.

PS: You will need to change the link on top of the project for this: http://henrychavez.github.io/materialize-tags/

Thanks a lot,

Jonathan

**Comment by henrychavez** [comment]
@DEKHTIARJonathan done!
