### ISSUE TITLE
After Tab key if there aren't any new values continue next input element in the form

### ISSUE THREAD

**Issue by alivelimeli** [henrychavez/materialize-tags#52]
Hello,

After tags are entered, selected and completed, when focus is on the tags input, after pressing Tab key, focus should move next input field.

Is there an option to get this functionality in materialize-tags library?

Thanks

**Comment by DEKHTIARJonathan** [comment]
The tab key is intercepted as a separator for tags. So I guess the functionality to move from field to field is disabled.
It would be possible, I guess, to create a new option to bypass this behavior, PR are welcome 👍

**Comment by henrychavez** [comment]
@alivelimeli This behavior can be allowed using the new option `allowTabOnEmpty : true` in this new version of the plugin 😄
