### ISSUE TITLE
Too early initialization in typeahead docs

### ISSUE THREAD

**Issue by Jarlskov** [henrychavez/materialize-tags#54]
In the docs for all examples describing how to use typeaheadjs the first line of "show code" is defines the input field as:

```<input type="text" value="Amsterdam,Washington" data-role="materialtags"/>```

This seems to initialize the materialize-tags plugin for the field without typeaheadjs. When you then try to set the typeahead settings with `$('input').materialtags({typeahead: {}});` the jQuery plugin can't find the `typeahead` option on the field settings.

Removing `data-role="materialtags"` solves the issue, and allows initializing the plugin with typeaheadjs enabled.

**Comment by henrychavez** [comment]
Yes, you are right.

Thanks for that, I'll update the docs.
