### ISSUE TITLE
issue with value when setting maxTags?

### ISSUE THREAD

**Issue by snehkantdev** [henrychavez/materialize-tags#56]
i have just used this tags plugin with yii framwork and i have found that when i set the maxTags to 1 or 2 tags ,the tags are displaying fine but the input field value remain blank i am not able to store it in database help?

**Comment by henrychavez** [comment]
Hi,
a quick solution until I finish some improvements to the code is if you want 1 tag you need to set the maxTags to 2.

this is the logic right now

`self.options.maxTags && self.itemsArray.length >= self.options.maxTags`

this logic needs some change but until that you can do what I described you.

**Comment by snehkantdev** [comment]
actually i am using this plugin with yii2 framwork and tags limit are not working as well as value are not displaying on server side with post variable
