### ISSUE TITLE
material tags does not work

### ISSUE THREAD

**Issue by wotta** [henrychavez/materialize-tags#6]
Hello,

I am using your plugin and did what I needed to do.
Now when I inspect the element it does not show that the div with ".materialize-tags" does not hold any css.

How can I fix this ?

**Comment by wotta** [comment]
?

**Comment by henrychavez** [comment]
check if the css file for materialize-tags is linked

2015-12-11 15:44 GMT-05:00 Wouter van Marrum notifications@github.com:

> ?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/henrychavez/materialize-tags/issues/6#issuecomment-164043169
> .

## 

Henry G. Chávez Vergara.
Design, Web & Mobile Development
Phone: +(51) 944119329
Email: henry19.chavez@gmail.com
Lima - Perú
