### ISSUE TITLE
Publish to bower & npm

### ISSUE THREAD

**Issue by ngryman** [henrychavez/materialize-tags#7]
Would be awesome! :)

**Comment by ngryman** [comment]
@henrychavez Would you like me to make a PR adding a `package.json` for `devDependencies` and to publish in on `npm`?

**Comment by henrychavez** [comment]
I already did but if you want make it in bower will be awesome

let me know

2015-11-28 8:55 GMT-05:00 Nicolas Gryman notifications@github.com:

> @henrychavez https://github.com/henrychavez Would you like me to make a
> PR adding a package.json for devDependencies and to publish in on npm?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/henrychavez/materialize-tags/issues/7#issuecomment-160297835
> .

## 

Henry G. Chávez Vergara.
Design, Web & Mobile Development
Phone: +(51) 944119329
Email: henry19.chavez@gmail.com
Lima - Perú

**Comment by ngryman** [comment]
**Bower** only needs to register the package once, further publishes are done automatically when you create git tags. I think you should do it because it asks some project specific questions.

At the root of the project:

``` bash
npm i -g bower
bower init # interactive questions
bower register materialize-tags git://github.com/henrychavez/materialize-tags.git
```

That's it!

ref: http://bower.io/docs/creating-packages/
